### ISSUE TITLE
How to: alternate income stream

### ISSUE THREAD

**Issue by PyGeek03** [viet-aus-it/meetup-planning#14]
## Context

It's FIRE time 🔥🔥🔥 Also hedge against re-orgs and lay-offs

## Resources

- Barefoot Investor
- Redbubble?
- Freelance work: https://www.hostinger.com/tutorials/best-freelance-websites
- https://www.bankrate.com/investing/passive-income-ideas

**Comment by samhwang** [comment]
Addressed on 12/03/2023.
