### ISSUE TITLE
Imposter Syndrome

### ISSUE THREAD

**Issue by maidoesstuff** [viet-aus-it/meetup-planning#4]
## Context

>Impostor syndrome (also known as impostor phenomenon or impostorism) is a psychological occurrence in which an individual doubts their skills, talents, or accomplishments and has a persistent [internalized](https://en.wikipedia.org/wiki/Internalizing_disorder) fear of being exposed as a fraud. Despite external evidence of their competence, those experiencing this phenomenon do not believe they deserve their success or luck. They may incorrectly attribute it to the [Matthew effect](https://en.wikipedia.org/wiki/Matthew_effect), or they may think that they are deceiving others because they feel as if they are not as intelligent as they outwardly portray themselves to be. Impostor syndrome can stem from and result in strained personal relationships and can hinder individuals from achieving their full potential in their fields of interest. When impostor syndrome was first conceptualized, it was viewed as a phenomenon that was common among high-achieving females. However, further research has shown that it affects both males and females equally.

>Individuals with imposter syndrome often have corresponding mental health issues, which may be treated with psychological interventions, though the phenomenon is not a formal mental disorder.

## Resources

[https://en.wikipedia.org/wiki/Impostor_syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome)

**Comment by samhwang** [comment]
Bump this one up
